### ISSUE TITLE
Can't import module with error: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by DrummerViking** [reflex-dev/reflex-ag-grid#14]
I'm failing to import the library.

My file where I want to use it has:
**from __future__ import annotations
from .. import styles
from ..templates import template
import pandas as pd
from reflex_ag_grid import ag_grid
import reflex as rx**

only just by importing it, it fails to start the app with error:

Warning: Windows Subsystem for Linux (WSL) is recommended for improving initial install times.
──────────────────────────────────────────────────────────────────────── 
Starting Reflex App ─────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
.......... 
File "C:\dev\projectFolder\pages\about_version_history.py", line 7, in <module>
    from reflex_ag_grid import ag_grid
  File "C:\Users\userprofile\AppData\Roaming\Python\Python39\site-packages\reflex_ag_grid_init_.py", line 1, in <module>
    from .ag_grid import *
  File "C:\Users\userprofile\AppData\Roaming\Python\Python39\site-packages\reflex_ag_grid\ag_grid.py", line 10, in <module>
    from .datasource import Datasource, SSRMDatasource
  File "C:\Users\userprofile\AppData\Roaming\Python\Python39\site-packages\reflex_ag_grid\datasource.py", line 10, in <module>
    class Datasource(Base):
  **File "C:\Users\userprofile\AppData\Roaming\Python\Python39\site-packages\reflex_ag_grid\datasource.py", line 11, in Datasource
    uri: str | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'**

versions:
python                             3.9.12
reflex                               0.6.1
reflex-ag-grid                       0.0.5

is there any backward compatibility issue maybe with python version 3.9.xx ?

**Comment by DrummerViking** [comment]
it is a company wise standard to keep version 3.9.
but i will insist to upgrade to version 3.10
you can close this issue.
